/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author Aditya
 */
public class Home_Form extends javax.swing.JFrame {

    /**
     * Creates new form Home_Form
     * @param username
     */
    public Home_Form(String username) {
        initComponents();
        if(!username.equals("admin"))
        {
            jSeparator4.setVisible(false);
            jLabel_user.setVisible(false);
            jSeparator5.setVisible(false);
            jLabel_company.setVisible(false);
        }
        //String path = "/src/images/bgImage.jpeg";
        //ImageIcon image = new javax.swing.ImageIcon(getClass().getResource("/images/bgImage.jpeg"));
        //String str = image.
        //jLabel_bgImage.setIcon(ResizeImage(path, null));
    
    }
    
    private ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;
        
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jLabel_bgImage.getWidth(), jLabel_bgImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_product = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_category = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_customer = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_order = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_user = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel_company = new javax.swing.JLabel();
        jLabel_bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BABA HARWARES and Building Material Suppliers");
        setIconImage((new ImageIcon("img.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jLabel_product.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_product.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_product.setText("PRODUCT");
        jLabel_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_productMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_productMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_productMouseExited(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_category.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_category.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_category.setText("CATEGORY");
        jLabel_category.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_categoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_categoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_categoryMouseExited(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_customer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_customer.setText("CUSTOMER");
        jLabel_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_customerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_customerMouseExited(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_order.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_order.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_order.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_order.setText("ORDER");
        jLabel_order.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_orderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_orderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_orderMouseExited(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_user.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user.setText("USER");
        jLabel_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_userMouseExited(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_company.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_company.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_company.setText("COMPANY");
        jLabel_company.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_company.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_companyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_companyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_companyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_product)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_category)
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_customer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_order)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_company)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_user)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator4))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_company)
                            .addComponent(jLabel_product))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel_bgImage.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel_bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laptop.jpg"))); // NOI18N
        jLabel_bgImage.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_bgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 1394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_bgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 622, Short.MAX_VALUE))
        );

        //ImageIcon myImage = new javax.swing.ImageIcon(getClass().getResource("/images/bgImage.jpeg"));
        //Image img = myImage.getImage();
        //Image img2 = img.getScaledInstance(jLabel_bgImage.getWidth(), jLabel_bgImage.getHeight(), Image.SCALE_SMOOTH);
        //ImageIcon image = new ImageIcon(img2);
        //jLabel_bgImage.setIcon(image);
        //set image to the jlabel
        //jLabel_bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgImage.jpeg")));

        /*
        ImageIcon myImage = new ImageIcon(getClass().getResource("/images/username_field.png"));

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jLabel_bgImage.getWidth(), jLabel_bgImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        jLabel_bgImage.setIcon(image);*/
        /*
        try
        {
            BufferedImage image = ImageIO.read(new File("./src/images/oil.jpeg"));
            //JLabel label = new JLabel(new ImageIcon(image));
            ImageIcon myImage = new ImageIcon(image);
            jLabel_bgImage.setIcon(myImage);
            Image img = myImage.getImage();
            Image img2 = img.getScaledInstance(jLabel_bgImage.getWidth(), jLabel_bgImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image1 = new ImageIcon(img2);
            jLabel_bgImage.setIcon(image1);
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }*/

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        /*try
        {
            BufferedImage image = ImageIO.read(new File("./src/images/bgImage.jpeg"));
            JLabel label = new JLabel(new ImageIcon(image));
            jPanel1.add(label);
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }*/

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,204,204));
        jLabel_user.setBorder(label_border);
        jLabel_user.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_userMouseEntered

    private void jLabel_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userMouseExited
        
        Border label_border = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.white);
        jLabel_user.setBorder(label_border);
        jLabel_user.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_userMouseExited

    private void jLabel_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userMouseClicked
        MANAGE_USERS_FORM uf = new MANAGE_USERS_FORM();
        uf.setVisible(true);
        uf.pack();
        uf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        uf.setLocationRelativeTo(null);
        //this.dispose();
    }//GEN-LAST:event_jLabel_userMouseClicked

    private void jLabel_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_productMouseClicked
        // TODO add your handling code here:
        MANAGE_PRODUCTS_FORM pf = new MANAGE_PRODUCTS_FORM();
        pf.setVisible(true);
        pf.pack();
        pf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pf.setLocationRelativeTo(null);
        pf.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel_productMouseClicked

    private void jLabel_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_categoryMouseClicked
        // TODO add your handling code here:
        MANAGE_CATEGORIES_FORM cf = new MANAGE_CATEGORIES_FORM();
        cf.setVisible(true);
        cf.pack();
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cf.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel_categoryMouseClicked

    private void jLabel_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_customerMouseClicked
        // TODO add your handling code here:
        MANAGE_CUSTOMERS_FORM cf = new MANAGE_CUSTOMERS_FORM();
        cf.setVisible(true);
        cf.pack();
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cf.setLocationRelativeTo(null);
        cf.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel_customerMouseClicked

    private void jLabel_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_orderMouseClicked
        // TODO add your handling code here:
        MANAGE_ORDERS_FORM of = new MANAGE_ORDERS_FORM();
        of.setVisible(true);
        of.pack();
        of.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        of.setLocationRelativeTo(null);
        of.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jLabel_orderMouseClicked

    private void jLabel_orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_orderMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,204,204));
        jLabel_order.setBorder(label_border);
        jLabel_order.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_orderMouseEntered

    private void jLabel_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_customerMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,204,204));
        jLabel_customer.setBorder(label_border);
        jLabel_customer.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_customerMouseEntered

    private void jLabel_categoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_categoryMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,204,204));
        jLabel_category.setBorder(label_border);
        jLabel_category.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_categoryMouseEntered

    private void jLabel_productMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_productMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,204,204));
        jLabel_product.setBorder(label_border);
        jLabel_product.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_productMouseEntered

    private void jLabel_orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_orderMouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(204,204,204));
        jLabel_order.setBorder(label_border);
        jLabel_order.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_orderMouseExited

    private void jLabel_customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_customerMouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(204,204,204));
        jLabel_customer.setBorder(label_border);
        jLabel_customer.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_customerMouseExited

    private void jLabel_categoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_categoryMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(204,204,204));
        jLabel_category.setBorder(label_border);
        jLabel_category.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_categoryMouseExited

    private void jLabel_productMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_productMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(204,204,204));
        jLabel_product.setBorder(label_border);
        jLabel_product.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_productMouseExited

    private void jLabel_companyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_companyMouseClicked
        // TODO add your handling code here:
        MANAGE_COMPANY_DETAILS_FORM of = new MANAGE_COMPANY_DETAILS_FORM();
        of.setVisible(true);
        of.pack();
        of.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        of.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel_companyMouseClicked

    private void jLabel_companyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_companyMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204,204,204));
        jLabel_company.setBorder(label_border);
        jLabel_company.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jLabel_companyMouseEntered

    private void jLabel_companyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_companyMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.white);
        jLabel_company.setBorder(label_border);
        jLabel_company.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_companyMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Form("admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_bgImage;
    private javax.swing.JLabel jLabel_category;
    private javax.swing.JLabel jLabel_company;
    private javax.swing.JLabel jLabel_customer;
    private javax.swing.JLabel jLabel_order;
    private javax.swing.JLabel jLabel_product;
    private javax.swing.JLabel jLabel_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
