/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import CLASS.Category;
import CLASS.IDGenerator;
import CLASS.Myfunc;
import CLASS.Product;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aditya
 */
public class MANAGE_PRODUCT_CATEGORIES_FORM extends javax.swing.JFrame {
    ArrayList<Category> list;
    /**
     * Creates new form MANAGE_CATEGORIES_FORM
     */
    public MANAGE_PRODUCT_CATEGORIES_FORM() {
        initComponents();
        try {
            list = Myfunc.getProductCategoryList();
        } catch (SQLException ex) {
            Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Problem Loading Product Categories : " + ex.getMessage());
            this.dispose();
        }
        Show_Product_Category_in_JTable();
    }
    
    private void Show_Product_Category_in_JTable() {
        DefaultTableModel model = (DefaultTableModel)jTable_category.getModel();
        // clear jtable content
        model.setRowCount(0);
        int noOfColumns = 2;        // number of columns in user table
        Object[] row = new Object[noOfColumns];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_id1 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        jButton_next = new javax.swing.JButton();
        jButton_previous = new javax.swing.JButton();
        jButton_insertNewCategory = new javax.swing.JButton();
        jButton_updateSelectedCategory = new javax.swing.JButton();
        jButton_deleteSelectedCategory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_category = new javax.swing.JTable();
        jButton_showProductList = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_item = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRODUCT CATEGORIES");
        setIconImage((new ImageIcon("img.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id.setText("Name :");

        jLabel_id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_id1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id1.setText("ID :");

        jTextField_id.setEditable(false);

        jButton_next.setText("Next");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });

        jButton_previous.setText("Previous");
        jButton_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_previousActionPerformed(evt);
            }
        });

        jButton_insertNewCategory.setBackground(new java.awt.Color(0, 153, 0));
        jButton_insertNewCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_insertNewCategory.setForeground(new java.awt.Color(255, 255, 255));
        jButton_insertNewCategory.setText("Insert New Category");
        jButton_insertNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertNewCategoryActionPerformed(evt);
            }
        });

        jButton_updateSelectedCategory.setBackground(new java.awt.Color(0, 153, 204));
        jButton_updateSelectedCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_updateSelectedCategory.setForeground(new java.awt.Color(255, 255, 255));
        jButton_updateSelectedCategory.setText("Update Selected Category");
        jButton_updateSelectedCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateSelectedCategoryActionPerformed(evt);
            }
        });

        jButton_deleteSelectedCategory.setBackground(new java.awt.Color(255, 0, 102));
        jButton_deleteSelectedCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_deleteSelectedCategory.setForeground(new java.awt.Color(255, 255, 255));
        jButton_deleteSelectedCategory.setText("Delete Selected Category");
        jButton_deleteSelectedCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteSelectedCategoryActionPerformed(evt);
            }
        });

        jTable_category.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_categoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_category);

        jButton_showProductList.setBackground(new java.awt.Color(204, 0, 204));
        jButton_showProductList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_showProductList.setForeground(new java.awt.Color(255, 255, 255));
        jButton_showProductList.setText("Show full Products List in this Category");
        jButton_showProductList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showProductListActionPerformed(evt);
            }
        });

        jList_item.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList_item);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<< Products in the Selected Category >>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_insertNewCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel_id)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton_updateSelectedCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_deleteSelectedCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton_showProductList, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_showProductList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_id))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_next)
                            .addComponent(jButton_previous))
                        .addGap(50, 50, 50)
                        .addComponent(jButton_insertNewCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_updateSelectedCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_deleteSelectedCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_categoryMouseClicked
        // TODO add your handling code here:
        int index = jTable_category.getSelectedRow();
        
        Category category = list.get(index);
        
        jTextField_id.setText(category.getId());
        jTextField_name.setText(category.getName());
        
        ArrayList<Product> productsInCategoryList;
        try {
            productsInCategoryList = Myfunc.getProductsInCategory_by_CategoryID(category.getId());
        } catch (SQLException ex) {
            Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Problem loading Products in The Selected Category : " + ex.getMessage());
            return;
        }
        String[] listData =  new String[productsInCategoryList.size()];
        int i = 0;
        for(Product product : productsInCategoryList)
        {
            listData[i++] = product.getName();
        }
        jList_item.setListData(listData);
    }//GEN-LAST:event_jTable_categoryMouseClicked

    // Check Input Fields
    public boolean checkInputs()
    {
        if(
              jTextField_name.getText() == null
              || jTextField_name.getText().equals("")
          ){
            return false;
        }
        else{
            try{
                //Float.parseFloat(txt_price.getText());
                // TODO check phone number and email
                return true;
            }catch(Exception ex)
            {
                return false;
            }
        }
    }
    
    private void jButton_insertNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertNewCategoryActionPerformed
        // TODO add your handling code here:
        if(checkInputs())
        {
            Connection con = null;
            PreparedStatement ps = null;
            Savepoint savepoint1 = null;
            
            try {
                con = My_CNX.getConnection();
                //System.out.println("database connected");
                con.setAutoCommit(false);
                //set a Savepoint
                savepoint1 = con.setSavepoint("Savepoint1");
                
                ps = con.prepareStatement("INSERT INTO product_category(id,Name)"
                        + "values(?,?) ");
                ps.setString(1, IDGenerator.getIDforProductCategory());
                ps.setString(2, jTextField_name.getText());
             
                ps.executeUpdate();
                ps.close();
                con.commit();
                con.close();
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null,"ADDING PRODUCT CATEGORY FAILED : " + ex.getMessage());
                try {
                    if(con != null) {
                        con.rollback(savepoint1);
                    }
                } catch (SQLException ex1) {
                    Logger.getLogger(MANAGE_ORDERS_FORM.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }finally
            {
                try { if(ps != null)  ps.close(); } catch(SQLException e){}
                try { if(con != null)  con.close(); } catch(SQLException e){}
                try {
                    list = Myfunc.getProductCategoryList();
                    Show_Product_Category_in_JTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Product Category List could Not Be Refreshed : " + ex.getMessage());
                    this.dispose();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "One Or More Field Are Empty");
        }
    }//GEN-LAST:event_jButton_insertNewCategoryActionPerformed

    private void jButton_updateSelectedCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateSelectedCategoryActionPerformed
        // TODO add your handling code here:
        if(checkInputs())
        {
            int i = JOptionPane.showConfirmDialog(null, "UPDATING THE CATEGORY NAME! ARE YOU SURE??", "WARNING",JOptionPane.YES_NO_OPTION );
            if(i != 0) return;      //NO
            Connection con = null;
            PreparedStatement ps = null;
            Savepoint savepoint1 = null;
            
            try {
                con = My_CNX.getConnection();
                //System.out.println("database connected");
                 con.setAutoCommit(false);
                //set a Savepoint
                savepoint1 = con.setSavepoint("Savepoint1");
                
                ps = con.prepareStatement("UPDATE product_category SET Name = ? "
                + " WHERE id = ?");   
                ps.setString(1, jTextField_name.getText());
                ps.setString(2, jTextField_id.getText());
                ps.executeUpdate();
                 ps.close();
                con.commit();
                con.close();
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null,"UPDATING PRODUCT CATEGORY FAILED : " + ex.getMessage());
                try {
                    if(con != null) {
                        con.rollback(savepoint1);
                    }
                } catch (SQLException ex1) {
                    Logger.getLogger(MANAGE_ORDERS_FORM.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }finally
            {
                try { if(ps != null)  ps.close(); } catch(SQLException e){}
                try { if(con != null)  con.close(); } catch(SQLException e){}
                try {
                    list = Myfunc.getProductCategoryList();
                    Show_Product_Category_in_JTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "PRODUCT Category List could Not Be Refreshed : " + ex.getMessage());
                    this.dispose();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "One Or More Field Are Empty");
        }
    }//GEN-LAST:event_jButton_updateSelectedCategoryActionPerformed

    private void jButton_deleteSelectedCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteSelectedCategoryActionPerformed
        // TODO add your handling code here:
        if(!jTextField_id.getText().equals(""))
        {
            int i = JOptionPane.showConfirmDialog(null, "DELETING the PRODUCT CATEGORY! ALL THE PRODUCTS IN THIS CATEGORY WILL ALSO BE DELETED!  ARE YOU SURE??", "WARNING",JOptionPane.YES_NO_OPTION );
            if(i != 0) return;      //NO
            Connection con = null;
            PreparedStatement ps = null;
            Savepoint savepoint1 = null;
            
            try {
                con = My_CNX.getConnection();
                con.setAutoCommit(false);
                //set a Savepoint
                savepoint1 = con.setSavepoint("Savepoint1");
                ps = con.prepareStatement("DELETE FROM product_category WHERE id = ?");
                String id = jTextField_id.getText();
                ps.setString(1, id);
                ps.executeUpdate();
                 ps.close();
                con.commit();
                con.close();
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null,"DELETING CUSTOMER CATEGORY FAILED : " + ex.getMessage());
                try {
                    if(con != null) {
                        con.rollback(savepoint1);
                    }
                } catch (SQLException ex1) {
                    Logger.getLogger(MANAGE_ORDERS_FORM.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }finally
            {
                try { if(ps != null)  ps.close(); } catch(SQLException e){}
                try { if(con != null)  con.close(); } catch(SQLException e){}
                try {
                    list = Myfunc.getProductCategoryList();
                    Show_Product_Category_in_JTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Product Category List could Not Be Refreshed : " + ex.getMessage());
                    this.dispose();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Product Category Not Deleted : No Id To Delete");
        }
    }//GEN-LAST:event_jButton_deleteSelectedCategoryActionPerformed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        // TODO add your handling code here:
        int index = jTable_category.getSelectedRow();
        System.out.println(index);
        if(index >= 0 && index < (jTable_category.getRowCount()-1))
        {
            index++;
            jTable_category.setRowSelectionInterval(index, index);
            Category category = list.get(index);

            jTextField_id.setText(category.getId());
            jTextField_name.setText(category.getName());

            ArrayList<Product> productsInCategoryList;
            try {
                productsInCategoryList = Myfunc.getProductsInCategory_by_CategoryID(category.getId());
            } catch (SQLException ex) {
                Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Problem loading Products in The Selected Category : " + ex.getMessage());
                return;
            }
            String[] listData =  new String[productsInCategoryList.size()];
            int i = 0;
            for(Product product : productsInCategoryList)
            {
                listData[i++] = product.getName();
            }
            jList_item.setListData(listData);
        }
    }//GEN-LAST:event_jButton_nextActionPerformed

    private void jButton_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_previousActionPerformed
        // TODO add your handling code here:
        int index = jTable_category.getSelectedRow();
        System.out.println(index);
        if(index > 0 && index < jTable_category.getRowCount())
        {
            index--;
            jTable_category.setRowSelectionInterval(index, index);
            Category category = list.get(index);

            jTextField_id.setText(category.getId());
            jTextField_name.setText(category.getName());

            ArrayList<Product> productsInCategoryList;
            try {
                productsInCategoryList = Myfunc.getProductsInCategory_by_CategoryID(category.getId());
            } catch (SQLException ex) {
                Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Problem loading Products in The Selected Category : " + ex.getMessage());
                return;
            }
            String[] listData =  new String[productsInCategoryList.size()];
            int i = 0;
            for(Product product : productsInCategoryList)
            {
                listData[i++] = product.getName();
            }
            jList_item.setListData(listData);
        }
    }//GEN-LAST:event_jButton_previousActionPerformed

    private void jButton_showProductListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showProductListActionPerformed
        // TODO add your handling code here:
        if(!jTextField_id.getText().equals(""))
        {
            try
            {
                PRODUCTS_IN_CATEGORY_FORM pcf;
                pcf = new PRODUCTS_IN_CATEGORY_FORM(Myfunc.getProductCategory(jTextField_id.getText(),false));
                pcf.setVisible(true);
                pcf.pack();
                pcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                pcf.setLocationRelativeTo(null);
                pcf.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }catch(Exception ex)
            {
                Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Problem loading Products in The Selected Category : " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton_showProductListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGE_PRODUCT_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGE_PRODUCT_CATEGORIES_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_deleteSelectedCategory;
    private javax.swing.JButton jButton_insertNewCategory;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_previous;
    private javax.swing.JButton jButton_showProductList;
    private javax.swing.JButton jButton_updateSelectedCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_id1;
    private javax.swing.JList<String> jList_item;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_category;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables

    
}
