/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Aditya
 */
public class MANAGE_CATEGORIES_FORM extends javax.swing.JFrame {

    /**
     * Creates new form MANAGE_CATEGORIES_FORM
     */
    public MANAGE_CATEGORIES_FORM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_productCategory = new javax.swing.JButton();
        jButton_unitCategory = new javax.swing.JButton();
        jButton_customerCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MANAGE CATEGORIES");
        setIconImage((new ImageIcon("img.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jButton_productCategory.setBackground(new java.awt.Color(0, 153, 51));
        jButton_productCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_productCategory.setForeground(new java.awt.Color(255, 255, 255));
        jButton_productCategory.setText("MANAGE PRODUCT CATEGORIES");
        jButton_productCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_productCategoryActionPerformed(evt);
            }
        });

        jButton_unitCategory.setBackground(new java.awt.Color(255, 204, 0));
        jButton_unitCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_unitCategory.setForeground(new java.awt.Color(255, 255, 255));
        jButton_unitCategory.setText("MANAGE UNIT CATEGORIES");
        jButton_unitCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_unitCategoryActionPerformed(evt);
            }
        });

        jButton_customerCategory.setBackground(new java.awt.Color(0, 102, 204));
        jButton_customerCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_customerCategory.setForeground(new java.awt.Color(255, 255, 255));
        jButton_customerCategory.setText("MANAGE CUSTOMER CATEGORIES");
        jButton_customerCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_customerCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_productCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_unitCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_customerCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton_productCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton_unitCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton_customerCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_unitCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_unitCategoryActionPerformed
 
        MANAGE_UNIT_CATEGORIES_FORM cf = new MANAGE_UNIT_CATEGORIES_FORM();
        cf.setVisible(true);
        cf.pack();
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_unitCategoryActionPerformed

    private void jButton_customerCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_customerCategoryActionPerformed
 
        MANAGE_CUSTOMER_CATEGORIES_FORM cf = new MANAGE_CUSTOMER_CATEGORIES_FORM();
        cf.setVisible(true);
        cf.pack();
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_customerCategoryActionPerformed

    private void jButton_productCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_productCategoryActionPerformed
        // TODO add your handling code here:
        MANAGE_PRODUCT_CATEGORIES_FORM cf = new MANAGE_PRODUCT_CATEGORIES_FORM();
        cf.setVisible(true);
        cf.pack();
        cf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_productCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CATEGORIES_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGE_CATEGORIES_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_customerCategory;
    private javax.swing.JButton jButton_productCategory;
    private javax.swing.JButton jButton_unitCategory;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
