/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import CLASS.Customer;
import CLASS.IDGenerator;
import CLASS.Myfunc;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aditya
 */
public class MANAGE_CUSTOMERS_FORM extends javax.swing.JFrame {
    ArrayList<Customer> list;
    /**
     * Creates new form MANAGE_CUSTOMERS_FORM
     */
    public MANAGE_CUSTOMERS_FORM() {
        initComponents();
        try {
            list = Myfunc.getCustomerList();
        } catch (SQLException ex) {
            Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,"Problem Loading the Customer List : " + ex.getMessage());
            this.dispose();
        }
        Show_Customer_In_JTable();
       
        jTextField_id.setText(IDGenerator.getIDforCustomer());
        jLabel_orderCount.setText("###");
        jLabel_totalOrderAmount.setText("###");
        jLabel_lastOrderDate.setText("###");
        jLabel_balance.setText("###");
    }
    
    private void Show_Customer_In_JTable()
    {
        DefaultTableModel model = (DefaultTableModel)jTable_customers.getModel();
        // clear jtable content
        model.setRowCount(0);
        int noOfColumns = 5;        // number of columns in user table
        Object[] row = new Object[noOfColumns];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getFirstName();
            row[2] = list.get(i).getLastName();
            row[3] = list.get(i).getPhone();
            row[4] = list.get(i).getEmail();
            model.addRow(row);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_customers = new javax.swing.JTable();
        jButton_insert = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_fullname = new javax.swing.JLabel();
        jLabel_telephone = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jButton_clear = new javax.swing.JButton();
        jTextField_id = new javax.swing.JTextField();
        jTextField_firstName = new javax.swing.JTextField();
        jTextField_lastName = new javax.swing.JTextField();
        jTextField_telephone = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jButton_refreshID = new javax.swing.JButton();
        jLabel_email1 = new javax.swing.JLabel();
        jComboBox_customerCategory = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_totalOrderAmount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_orderCount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_lastOrderDate = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_balance = new javax.swing.JLabel();
        jTextField_GSTIN = new javax.swing.JTextField();
        jLabel_email2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CUSTOMER");
        setIconImage((new ImageIcon("img.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jTable_customers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable_customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Telephone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_customersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_customers);

        jButton_insert.setBackground(new java.awt.Color(0, 153, 51));
        jButton_insert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_insert.setForeground(new java.awt.Color(255, 255, 255));
        jButton_insert.setText("Insert");
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });

        jButton_edit.setBackground(new java.awt.Color(0, 153, 255));
        jButton_edit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_remove.setBackground(new java.awt.Color(255, 102, 102));
        jButton_remove.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        jLabel_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_id.setText("ID:");

        jLabel_username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_username.setText("First Name");

        jLabel_fullname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_fullname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fullname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_fullname.setText("Last Name:");

        jLabel_telephone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_telephone.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telephone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_telephone.setText("Tel:");

        jLabel_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_email.setText("Email:");

        jButton_clear.setBackground(new java.awt.Color(255, 102, 51));
        jButton_clear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jTextField_id.setEditable(false);

        jTextField_telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telephoneKeyTyped(evt);
            }
        });

        jButton_refreshID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshIDActionPerformed(evt);
            }
        });

        jLabel_email1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_email1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_email1.setText("Type:");

        try
        {
            String[] list = Myfunc.getAllCustomerCategoryNames();
            jComboBox_customerCategory.setModel(new javax.swing.DefaultComboBoxModel<>(list));
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Problem Loading Customer Category : " + ex.getMessage());
            this.dispose();
        }

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Order Amount :");

        jLabel_totalOrderAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_totalOrderAmount.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_totalOrderAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_totalOrderAmount.setText("###");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel_totalOrderAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel_totalOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order Count :");

        jLabel_orderCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_orderCount.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_orderCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_orderCount.setText("###");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_orderCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_orderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Order Date :");

        jLabel_lastOrderDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_lastOrderDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_lastOrderDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_lastOrderDate.setText("###");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel_lastOrderDate, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel_lastOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 0, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Balance :");

        jLabel_balance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_balance.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_balance.setText("###");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel_balance, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        jLabel_email2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_email2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_email2.setText("GSTIN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_fullname)))
                                    .addComponent(jLabel_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_email1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_email2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_GSTIN)
                                    .addComponent(jTextField_email, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_id, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_refreshID))
                                    .addComponent(jComboBox_customerCategory, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_firstName)
                                    .addComponent(jTextField_lastName)
                                    .addComponent(jTextField_telephone)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_id)
                            .addComponent(jButton_refreshID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_username))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_fullname)
                            .addComponent(jTextField_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_telephone))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_email))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_email1)
                            .addComponent(jComboBox_customerCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_GSTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_email2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Show Data In Inputs
    public void ShowItem(int index) throws SQLException, Exception
    {
        Customer customer = list.get(index);
        jTextField_id.setText(customer.getId());
        jTextField_firstName.setText(customer.getFirstName());
        jTextField_lastName.setText(customer.getLastName());
        jTextField_telephone.setText(customer.getPhone());
        jTextField_email.setText(customer.getEmail());
        jTextField_GSTIN.setText(customer.getGSTIN());
        String catName = Myfunc.getCustomerCategoryName(customer.getCustomerCategoryID());
        jComboBox_customerCategory.setSelectedItem(catName);
        jLabel_orderCount.setText(Integer.toString(customer.getOrderCount()));
        jLabel_totalOrderAmount.setText("Rs." + Float.toString(customer.getTotalOrderAmount()) + "/-");
        Date date = customer.getLastOrderDate();
        if(date != null)
        jLabel_lastOrderDate.setText(date.toString());
        else
        jLabel_lastOrderDate.setText("###"); 
        jLabel_balance.setText("Rs." + Float.toString(customer.getBalance()) + "/-");
    }
    
    // Check Input Fields
    public boolean checkInputs()
    {
        if(
              jTextField_firstName.getText() == null
           || jTextField_telephone.getText() == null
           || jTextField_email.getText() == null
           || jTextField_lastName.getText() == null
                || jTextField_id.getText().equals("")
          ){
            return false;
        }
        else{
            try{
                //Float.parseFloat(txt_price.getText());
                // TODO check phone number and email
                return true;
            }catch(Exception ex)
            {
                return false;
            }
        }
    }
    
    private void jTable_customersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_customersMouseClicked

        int index = jTable_customers.getSelectedRow();
        try {
            ShowItem(index);
        } catch (Exception ex) {
            Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Problem Loading the details of this customer : " + ex.getMessage());
            //clear everything
            jTextField_id.setText(IDGenerator.getIDforCustomer());
            jTextField_lastName.setText("");
            jTextField_firstName.setText("");
            jTextField_telephone.setText("");
            jTextField_email.setText("");
            jTextField_GSTIN.setText("");
        }
    }//GEN-LAST:event_jTable_customersMouseClicked

    
    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement ps = null;
        Savepoint savepoint1 = null;
        if(checkInputs())
        {
            try {
                con = My_CNX.getConnection();
                //System.out.println("database connected");
                con.setAutoCommit(false);
                //set a Savepoint
                savepoint1 = con.setSavepoint("Savepoint1");
                
                ps = con.prepareStatement("INSERT INTO customer_table(id,FirstName,LastName,Phone,Email,OrderCount,TotalOrderAmount,LastOrderDate,Balance,AddDate,CustomerCategoryID,GSTIN)"
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?) ");
                ps.setString(1, jTextField_id.getText());
                ps.setString(3, jTextField_lastName.getText());
                ps.setString(2, jTextField_firstName.getText());
                ps.setString(4, jTextField_telephone.getText());
                ps.setString(5, jTextField_email.getText());
                ps.setString(6, "0");
                ps.setString(7, "0.0");
                ps.setString(8, null);
                ps.setString(9, "0.0"); 
                ps.setDate(10 , Myfunc.getCurrentDate());
                
                String cid = Myfunc.getCustomerCategoryID((String)jComboBox_customerCategory.getSelectedItem());
                ps.setString(11, cid );
                ps.setString(12, jTextField_GSTIN.getText());
               // System.out.println("before exe => " + cid);
                ps.executeUpdate();
                
                ps.close();
                con.commit();
                con.close();
               // System.out.println("before display");
                
               // System.out.println("inserted");
               JOptionPane.showMessageDialog(null, "CUSTOMER ADDED SUCCESSFULLY :-)");
               jTextField_id.setText(IDGenerator.getIDforCustomer());
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null,"ADDING CUSTOMER FAILED : " + ex.getMessage());
                try {
                    if(con != null) {
                        con.rollback(savepoint1);
                    }
                } catch (SQLException ex1) {
                    Logger.getLogger(MANAGE_ORDERS_FORM.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }finally
            {
                try { if(ps != null)  ps.close(); } catch(SQLException e){}
                try { if(con != null)  con.close(); } catch(SQLException e){}
                try {
                    list = Myfunc.getCustomerList();
                    Show_Customer_In_JTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Customer List could Not Be Refreshed : " + ex.getMessage());
                    this.dispose();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "One Or More Field Are Empty");
        }

        // only for test
        // System.out.println("Name => "+txt_name.getText());
        //  System.out.println("Price => "+txt_price.getText());
        //  System.out.println("Image => "+ImgPath);

    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed

        if(checkInputs() && jTextField_id.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = null;
            Savepoint savepoint1 = null;
            
            try {
                con = My_CNX.getConnection();
                con.setAutoCommit(false);
                //set a Savepoint
                savepoint1 = con.setSavepoint("Savepoint1");
                
                UpdateQuery = "UPDATE customer_table SET FirstName = ?, LastName = ?"
                + ", Phone = ? , Email = ? , CustomerCategoryID = ? , GSTIN = ? WHERE id = ?";
                ps = con.prepareStatement(UpdateQuery);
                //System.out.println(jTextField_id.getText());
                ps.setString(7, jTextField_id.getText());
                ps.setString(2, jTextField_lastName.getText());
                ps.setString(1, jTextField_firstName.getText());
                ps.setString(3, jTextField_telephone.getText());
                ps.setString(4, jTextField_email.getText());
                ps.setString(5, Myfunc.getCustomerCategoryID((String)jComboBox_customerCategory.getSelectedItem()));
                ps.setString(6, jTextField_GSTIN.getText());
                ps.executeUpdate();
                
                ps.close();
                con.commit();
                con.close();
                JOptionPane.showMessageDialog(null, "Data Updated Successfully :-)");

            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null,"UPDATING CUSTOMER DETAILS FAILED : " + ex.getMessage());
                try {
                    if(con != null) {
                        con.rollback(savepoint1);
                    }
                } catch (SQLException ex1) {
                    Logger.getLogger(MANAGE_ORDERS_FORM.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }finally
            {
                try { if(ps != null)  ps.close(); } catch(SQLException e){}
                try { if(con != null)  con.close(); } catch(SQLException e){}
                try {
                    list = Myfunc.getCustomerList();
                    Show_Customer_In_JTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Customer List could Not Be Refreshed : " + ex.getMessage());
                    this.dispose();
                }
            }
      
        }else{
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty Or Wrong");
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed

        if(!jTextField_id.getText().equals(""))
        {
            if(Float.parseFloat(jLabel_balance.getText().replace("Rs.","").replace("/-","")) != 0)
            {
                JOptionPane.showMessageDialog(null,"THE CUSTOMER CANNOT BE DELETED! THIS CUSTOMER HAS A BALANCE OF " + jLabel_balance.getText());
                return;
            }
            /*
            int i = JOptionPane.showConfirmDialog(null, "THIS CUSTOMER HAS A BALANCE OF " + jLabel_balance.getText() + "!  ARE YOU SURE??", "WARNING",JOptionPane.YES_NO_OPTION );
            if(i != 0) return;      //NO
            */
            int i = JOptionPane.showConfirmDialog(null, "ALL THE DETAILS OF THE CUSTOMER WILL BE LOST!  DO YOU WANT TO CONTINUE DELETING CUSTOMER'S DETAILS??", "WARNING",JOptionPane.YES_NO_OPTION );
            if(i != 0) return;      //NO
            Connection con = null;
            PreparedStatement ps = null;
            Savepoint savepoint1 = null;
            
            try {
                con = My_CNX.getConnection();
                con.setAutoCommit(false);
                //set a Savepoint
                savepoint1 = con.setSavepoint("Savepoint1");
                
                ps = con.prepareStatement("DELETE FROM customer_table WHERE id = ?");
                String id = jTextField_id.getText();
                ps.setString(1, id);
                ps.executeUpdate();
                ps.close();
                con.commit();
                con.close();
                //JOptionPane.showMessageDialog(null, "Data Updated");

            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,"DELETING CUSTOMER DETAILS FAILED : " + ex.getMessage());
                try {
                    if(con != null) {
                        con.rollback(savepoint1);
                    }
                } catch (SQLException ex1) {
                    Logger.getLogger(MANAGE_ORDERS_FORM.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }finally
            {
                try { if(ps != null)  ps.close(); } catch(SQLException e){}
                try { if(con != null)  con.close(); } catch(SQLException e){}
                try {
                    list = Myfunc.getCustomerList();
                    Show_Customer_In_JTable();
                } catch (SQLException ex) {
                    Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Customer List could Not Be Refreshed : " + ex.getMessage());
                    this.dispose();
                }
            }

        }else{
            JOptionPane.showMessageDialog(null, "Customer Not Deleted : No ID To Delete");
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        jTextField_id.setText(IDGenerator.getIDforCustomer());
        jTextField_lastName.setText("");
        jTextField_firstName.setText("");
        jTextField_telephone.setText("");
        jTextField_email.setText("");
        jTextField_GSTIN.setText("");
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jTextField_telephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telephoneKeyTyped

        // allow only numbers
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_telephoneKeyTyped

    private void jButton_refreshIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshIDActionPerformed
        // TODO add your handling code here:
        jTextField_id.setText(IDGenerator.getIDforCustomer());
    }//GEN-LAST:event_jButton_refreshIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGE_CUSTOMERS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGE_CUSTOMERS_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_refreshID;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JComboBox<String> jComboBox_customerCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_balance;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_email1;
    private javax.swing.JLabel jLabel_email2;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_lastOrderDate;
    private javax.swing.JLabel jLabel_orderCount;
    private javax.swing.JLabel jLabel_telephone;
    private javax.swing.JLabel jLabel_totalOrderAmount;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_customers;
    private javax.swing.JTextField jTextField_GSTIN;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_firstName;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_lastName;
    private javax.swing.JTextField jTextField_telephone;
    // End of variables declaration//GEN-END:variables
}
