/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import CLASS.Category;
import CLASS.Myfunc;
import CLASS.Product;
import CLASS.Product_detail;
import CLASS.TheModel;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aditya
 */
public class PRODUCTS_IN_CATEGORY_FORM extends javax.swing.JFrame {
    private Category category;
    ArrayList<Product> list;
    /**
     * Creates new form PRODUCTS_IN_CATEGORY_FORM
     */
    public PRODUCTS_IN_CATEGORY_FORM(Category category) {
        initComponents();
        this.category = category;
        try {
            list = Myfunc.getProductsInCategory_by_CategoryID(category.getId());
            Show_Products_in_Category_in_JTable();
        } catch (Exception ex) {
            Logger.getLogger(PRODUCTS_IN_CATEGORY_FORM.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Problem Loading Products in the Category : " + ex.getMessage());
            this.dispose();
        }
        jLabel_category.setText("PRODUCTS IN CATEGORY : " + category.getName());
    }

    /*private void Show_Products_in_Category_in_JTable() {
        DefaultTableModel model = (DefaultTableModel)jTable_products.getModel();
        // clear jtable content
        model.setRowCount(0);
        int noOfColumns = 6;        // number of columns in user table
        Object[] row = new Object[noOfColumns];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
           // System.out.println("ID => " + list.get(i).getCategoryID());
           // String Category = list.get(i).getCategoryID();
           // System.out.println("Name => " + Category);
            row[2] = category.getName();
            row[3] = list.get(i).getDescription();
            row[4] = list.get(i).getAddDate();
            row[5] = list.get(i).getImage();
      
            model.addRow(row);
        }
    }*/
    
    private void Show_Products_in_Category_in_JTable() throws Exception
    {
        String[] columnName = {"ID","Name","SubType","Description","Add Date","Image"};
        Object[][] rows = new Object[list.size()][6];
        for(int i = 0; i < list.size(); i++){
            rows[i][0] = list.get(i).getId();
            rows[i][1] = list.get(i).getName();
            rows[i][2] = list.get(i).getSubType();
            //String Category = pList.get(i).getCategoryID();
           // System.out.println("Name => " + Category);
            //rows[i][3] = Myfunc.getProductCategoryName(Category);
            rows[i][3] = list.get(i).getDescription();
            rows[i][4] = list.get(i).getAddDate();
            
            if(list.get(i).getImage() != null){
                
             ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getImage()).getImage()
             .getScaledInstance(150, 120, Image.SCALE_SMOOTH) );   
                
            rows[i][5] = image;
            }
            else{
                rows[i][5] = null;
            }
        }
        
        TheModel model = new TheModel(rows, columnName);
        jTable_products.setModel(model);
        jTable_products.setRowHeight(120);
        jTable_products.getColumnModel().getColumn(5).setPreferredWidth(150);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_category = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_products = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_product_detail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRODUCTS IN CATEGORY");
        setIconImage((new ImageIcon("img.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel_category.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_category.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_category.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_category.setText("PRODUCTS IN CATEGORY :");
        jLabel_category.setOpaque(true);

        jTable_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "SubType", "Description", "AddDate", "Picture"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_products);

        jTable_product_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Detail ID", "Unit Size", "Unit Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_product_detail.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable_product_detail);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_category, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_category, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Show_Product_Detail_in_JTable(Product product) throws SQLException, Exception
    {
        ArrayList<Product_detail> productList = Myfunc.getProductDetailList(product);
        DefaultTableModel model = (DefaultTableModel)jTable_product_detail.getModel();
        // clear jtable content
        model.setRowCount(0);
        int noOfColumns = 4;        // number of columns in user table
        Object[] row = new Object[noOfColumns];
       
        String unit = Myfunc.getUnitCategoryName(product.getUnitCategoryID());
        
        
        for(int i = 0; i < productList.size(); i++)
        {
            row[0] = productList.get(i).getId();
            row[1] = productList.get(i).getUnitSize() + "  " + unit; // TODO add the units(kg,lt,etc) here
            row[2] = productList.get(i).getUnitPrice();
            row[3] = productList.get(i).getQuantity();
      
            model.addRow(row);
        }
    }
    
    private void jTable_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productsMouseClicked
        // TODO add your handling code here:
        int index = jTable_products.getSelectedRow();
        Product product = list.get(index);
        try {
            Show_Product_Detail_in_JTable(product);
        } catch (Exception ex) {
            Logger.getLogger(PRODUCTS_IN_CATEGORY_FORM.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Problem Loading Details of this Product");
        }
    }//GEN-LAST:event_jTable_productsMouseClicked

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRODUCTS_IN_CATEGORY_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRODUCTS_IN_CATEGORY_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRODUCTS_IN_CATEGORY_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRODUCTS_IN_CATEGORY_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRODUCTS_IN_CATEGORY_FORM().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_category;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_product_detail;
    private javax.swing.JTable jTable_products;
    // End of variables declaration//GEN-END:variables
}
