/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import CLASS.Customer;
import CLASS.Generate_Receipt;
import CLASS.Myfunc;
import CLASS.Order;
import CLASS.Order_detail;
import CLASS.Product;
import CLASS.Product_detail;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aditya
 */
public class SELECTED_ORDER_FORM extends javax.swing.JFrame {
    ArrayList<Order_detail> list;
    Order order;
    /**
     * Creates new form SELECTED_ORDER_FORM
     * @param OrderID
     */
    public SELECTED_ORDER_FORM(String OrderID) {
        initComponents();
        try {
            order = Myfunc.getOrderByID(OrderID);
            list = Myfunc.getOrderDetailList_by_OrderID(OrderID);
            Show_OrderDetail(OrderID);
        } catch (Exception ex) {
            Logger.getLogger(SELECTED_ORDER_FORM.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "There is Some Problem With the Selected Order Details : " + ex.getMessage());
            this.dispose();
            //dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }
    
    private void Show_OrderDetail(String OrderID) throws Exception
    {
        DefaultTableModel model = (DefaultTableModel)jTable_order.getModel();
        // clear jtable content
        model.setRowCount(0);
        int noOfColumns = 8;        // number of columns in user table
        Object[] row = new Object[noOfColumns];
        //System.out.println(list.size());
        for(int i = 0; i < list.size(); i++)
        {
            Product_detail productDetail = Myfunc.getProductDetail_by_ProductDetailID(list.get(i).getproductDetailID(),true);
            //System.out.println("sof : " + productDetail.getId());
            row[0] = productDetail.getId();
            Product product = Myfunc.getProduct_by_ProductDetailID(list.get(i).getproductDetailID(),true);      // If not available generate
            row[1] = product.getName();
            row[2] = product.getSubType();
            
            row[3] = productDetail.getUnitSize() + " " + Myfunc.getUnitCategoryName(product.getUnitCategoryID());
           // System.out.println(row[2]);
            float price = list.get(i).getunitPrice();
            row[4] = price;
            float qty = list.get(i).getpurchasedQty();
            row[5] = qty;
            float discountPerUnit = list.get(i).getproductDiscountPrice();
            row[6] = discountPerUnit;
            row[7] = (price - discountPerUnit) * qty;
            model.addRow(row);
        }
        
        //Setting Other Things
        jLabel_orderID.setText(OrderID);
        jLabel_orderDate.setText(order.getOrderDate().toString());
        jLabel_customerID.setText(order.getCustomerID());
        Customer customer = Myfunc.getCustomerByID(order.getCustomerID(),true);
        jLabel_customerName.setText(customer.getFirstName() + " " + customer.getLastName());
        jLabel_discount.setText(Float.toString(order.getOverallDiscountPrice()) + "/-");
        jLabel_total.setText("Rs. " + Float.toString(order.getOrderAmount()) + "/-");
        jLabel_balance.setText("Rs. " + Float.toString(order.getBalance()) + "/-");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_orderID = new javax.swing.JLabel();
        jLabel_orderDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_customerID = new javax.swing.JLabel();
        jLabel_customerName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_order = new javax.swing.JTable();
        jButton_cancelOrder = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_discount = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jButton_payment = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_balance = new javax.swing.JLabel();
        jButton_generateReceipt = new javax.swing.JButton();
        jButton_deleteOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ORDER DETAILS");
        setIconImage((new ImageIcon("img.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ORDER ID :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ORDER DATE :");

        jLabel_orderID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_orderID.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_orderID.setText("###");

        jLabel_orderDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_orderDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_orderDate.setText("###");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_orderID, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_orderDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_orderID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CUST. ID :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CUST. NAME :");

        jLabel_customerID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_customerID.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_customerID.setText("###");

        jLabel_customerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_customerName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_customerName.setText("###");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_customerID, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_customerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTable_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "SubType", "Unit Size", "Unit Price (Rs.)", "Quantity", "Discount Price(Rs.)", "Amount (Rs.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_order);

        jButton_cancelOrder.setBackground(new java.awt.Color(255, 51, 51));
        jButton_cancelOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_cancelOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancelOrder.setText("CANCEL ORDER");
        jButton_cancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelOrderActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(" Overall DISCOUNT : Rs.");

        jLabel_discount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_discount.setText("0.0/-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(jLabel_discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText(" TOTAL AMOUNT :");

        jLabel_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_total.setText("Rs. 0.0/-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_total, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(jLabel_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton_payment.setBackground(new java.awt.Color(102, 204, 0));
        jButton_payment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_payment.setForeground(new java.awt.Color(255, 255, 255));
        jButton_payment.setText("PROCEED TO PAYMENT");
        jButton_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_paymentActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText(" Balance :");

        jLabel_balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_balance.setText("Rs. 0.0/-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addComponent(jLabel_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton_generateReceipt.setBackground(new java.awt.Color(0, 153, 255));
        jButton_generateReceipt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_generateReceipt.setForeground(new java.awt.Color(255, 255, 255));
        jButton_generateReceipt.setText("GENERATE RECEIPT");
        jButton_generateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_generateReceiptActionPerformed(evt);
            }
        });

        jButton_deleteOrder.setBackground(new java.awt.Color(255, 102, 102));
        jButton_deleteOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_deleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButton_deleteOrder.setText("DELETE ORDER");
        jButton_deleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_cancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_deleteOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_generateReceipt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_payment)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_cancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_deleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_generateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_paymentActionPerformed
        // TODO add your handling code here:
        String orderID = jLabel_orderID.getText();
        //DefaultTableModel orderModel = (DefaultTableModel)jTable_order.getModel();
        //orderModel.setRowCount(0);  //clear the order table
        PAYMENT_MODE_SELECTION_FORM pmf = new PAYMENT_MODE_SELECTION_FORM(orderID);
        pmf.setVisible(true);
        pmf.pack();
        pmf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pmf.setLocationRelativeTo(null);
        this.dispose();
        //dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton_paymentActionPerformed

    private void jButton_cancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelOrderActionPerformed
        // TODO add your handling code here:
        float total = Float.parseFloat(jLabel_total.getText().replace("Rs. ","").replace("/-",""));
        float balance = Float.parseFloat(jLabel_balance.getText().replace("Rs. ","").replace("/-",""));
        float paidAmount = total - balance;
        
        /*
        int j = JOptionPane.showConfirmDialog(null, "PAYMENT OF Rs." + paidAmount + "/- HAS BEEN DONE! ARE YOU SURE TO CANCEL THE ORDER??", "WARNING",JOptionPane.YES_NO_OPTION );
        if(j != 0) return;      //NO
        */
        if(paidAmount != 0)
        {
            JOptionPane.showMessageDialog(null,"CUSTOMER HAS PAID Rs." + paidAmount + "/- FOR THIS ORDER. ORDER CAN BE CANCELLED ONLY WHEN ALL THE MONEY IS RETURNED TO THE CUSTOMER!");
            return;
        }
        
        JOptionPane.showMessageDialog(null,"CANCELLING THE ORDER SHOULD BE DONE ONLY WHEN THE CUSTOMER IS \"RETURNING ALL THE ITEMS\"!\nRETURNING ITEMS WILL ADD THEM IN THE PRODUCT LIST,UPDATING THE DATABASE!\nIF THE CUSTOMER IS NOT RETURNING PRODUCTS YOU MIGHT WANT TO CONSIDER \"DELETING ORDER\" OPTION INSTEAD.");
        
        int j = JOptionPane.showConfirmDialog(null, "ARE YOU SURE TO CANCEL THE ORDER??", "WARNING",JOptionPane.YES_NO_OPTION );
        if(j != 0) return;      //NO
        
        DefaultTableModel orderModel = (DefaultTableModel)jTable_order.getModel();
        int rows = orderModel.getRowCount();
        
        //Connection con1 = null;   USING ARRAY INSTEAD!
        Connection con2 = null , con3 = null ;
        Connection con = null;
        Connection conArray[] = new Connection[rows];
        
        Savepoint savepoint = null; 
        try
        {
            con = My_CNX.getConnection();
            con.setAutoCommit(false);
            savepoint = con.setSavepoint("Savepoint1");     //IMPORTANT
            
            for(int i = 0 ; i < rows ; i++)
            {
                float purchasedQty = Float.parseFloat(orderModel.getValueAt(i, 5).toString());
                String productDetailID = orderModel.getValueAt(i, 0).toString();
                //con1 = Myfunc.addQuantityInDatabase(productDetailID,purchasedQty);
                try {
                    //JOptionPane.showMessageDialog(null,"PRODUCT DETAIL ID : " + productDetailID + "\tPURCHASED QTY : " +  purchasedQty);
                    //con1 = Myfunc.addQuantityInDatabase(productDetailID,purchasedQty,false);
                    //JOptionPane.showMessageDialog(null,"QUANTITY ADDED!");
                    /*
                        if you use only one variable 'con1' then only last loop's connection will commit
                        you need array of connections...COOL!
                    */
                    conArray[i] = Myfunc.addQuantityInDatabase(productDetailID,purchasedQty,false);
                }catch(Exception ex)
                {
                    //If the productDetailID is deleted
                    //JOptionPane.showMessageDialog(null,"Error in SELECTED_ORDER_FORM : ADDING QUANTITY : " + ex.getMessage());
                    //JOptionPane.showMessageDialog(null,ex.getMessage());
                    //if(!ex.getMessage().toLowerCase().contains("product detail id not found"))
                    //    throw ex;
                    //JOptionPane.showMessageDialog(null,ex.getMessage());
                    conArray[i] = null;
                }
            }
            //con2 = Myfunc.deleteOrder_by_OrderID(jLabel_orderID.getText());
            con2 = Myfunc.deleteOrder_by_OrderID(jLabel_orderID.getText(),false);
           //JOptionPane.showMessageDialog(null,"ORDER DELETED!");
            /*
                you don't need to delete anything from the order_detail table
                and the transaction_table bcoz they reference the order_table using foriegn key
                constraint "CASCADE ON DELETE"
                so you need to just delete order from the order_table..rest the database will do
            */
            String numberOnlyTotal = jLabel_total.getText().replace("Rs. ","").replace("/-","");
            //con3 = Myfunc.subtractOrderForCustomer(jLabel_customerID.getText(),Float.parseFloat(numberOnlyTotal));
            try
            {
                if(!jLabel_customerID.getText().toLowerCase().equals("general"))
                {
                    con3 = Myfunc.subtractOrderForCustomer(jLabel_customerID.getText(),Float.parseFloat(numberOnlyTotal),balance,false);
                    //JOptionPane.showMessageDialog(null, "PLEASE PAY BACK THE AMOUNT OF Rs." + paidAmount + "/- to CUSTOMER ID : " + jLabel_customerID.getText());
                    //or Add reverse transaction
                   // JOptionPane.showMessageDialog(null,"CUSTOMER UPDATED!");
                }
            }catch(Exception ex)
            {
                // If customer has been deleted!
               // JOptionPane.showMessageDialog(null,"Error in SELECTED_ORDER_FORM : UPDATING CUSTOMER : " + ex.getMessage());
                //if(!ex.getMessage().toLowerCase().contains("not found"))
                     //   throw ex;
                con3 = null;
            }
            JOptionPane.showMessageDialog(null, "Order with ID : " + jLabel_orderID.getText() + " CANCELED!");
        /*    if(con1 != null)
            {
                con1.commit();
                con1.close();
            }*/
        
            for(int i = 0 ; i < rows ; i++)
            {
                conArray[i].commit();
                conArray[i].close();
            }
            if(con2 != null)
            {
                con2.commit();
                con2.close();
            }
            if(con3 != null)
            {
                con3.commit();
                con3.close();
            }
            con.commit();
            con.close();
            //dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        //exit();
        }catch(Exception e)
        {
            try {
                if(con != null)
                con.rollback(savepoint);
            } catch (SQLException ex) {
                Logger.getLogger(SELECTED_ORDER_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        finally
        {
            for(int i = 0 ; i < rows ; i++) {try { if(conArray[i] != null)  conArray[i].close(); } catch(SQLException e){}}
            //try { if(con1 != null)  con1.close(); } catch(SQLException e){}
            try { if(con2 != null)  con2.close(); } catch(SQLException e){}
            try { if(con3 != null)  con3.close(); } catch(SQLException e){}
            try { if(con != null)  con.close(); } catch(SQLException e){}
        }
        this.dispose();
    }//GEN-LAST:event_jButton_cancelOrderActionPerformed

    private void jButton_generateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_generateReceiptActionPerformed
        // TODO add your handling code here:
        String OrderID = jLabel_orderID.getText();
        this.dispose();
        Generate_Receipt gr = new Generate_Receipt(OrderID);
    }//GEN-LAST:event_jButton_generateReceiptActionPerformed

    private void jButton_deleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteOrderActionPerformed
        // TODO add your handling code here:
        //float total = Float.parseFloat(jLabel_total.getText().replace("Rs. ","").replace("/-",""));
        float balance = Float.parseFloat(jLabel_balance.getText().replace("Rs. ","").replace("/-",""));
        //float paidAmount = total - balance;
        
        /*
        int j = JOptionPane.showConfirmDialog(null, "PAYMENT OF Rs." + paidAmount + "/- HAS BEEN DONE! ARE YOU SURE TO CANCEL THE ORDER??", "WARNING",JOptionPane.YES_NO_OPTION );
        if(j != 0) return;      //NO
        */
        if(balance != 0)
        {
            JOptionPane.showMessageDialog(null,"CUSTOMER HAS A BALANCE OF Rs." + balance + "/- FOR THIS ORDER. ORDER CAN BE DELETED ONLY WHEN ALL THE MONEY IS PAID BY THE CUSTOMER!");
            return;
        }
        
        JOptionPane.showMessageDialog(null,"DELETING THE ORDER WILL ONLY REMOVE THE ORDER AND RELATED TRANSACTIONS FROM THE LIST(DATABASE) FOREVER!\nTHE ORDER WILL NOT BE AVAILABLE FOR REFERENCE IN THE FUTURE!\nIF THE CUSTOMER IS RETURNING ALL THE ITEMS,YOU MIGHT WANT TO CONSIDER \"CANCEL ORDER\" OPTION.");
        
        int j = JOptionPane.showConfirmDialog(null, "ARE YOU SURE TO DELETE THE ORDER??", "WARNING",JOptionPane.YES_NO_OPTION );
        if(j != 0) return;      //NO
        
        //Connection con1 = null;   USING ARRAY INSTEAD!
        Connection con2 = null;
        Connection con = null;
        //Connection conArray[] = new Connection[rows];
        
        Savepoint savepoint = null; 
        try
        {
            con = My_CNX.getConnection();
            con.setAutoCommit(false);
            savepoint = con.setSavepoint("Savepoint1");     //IMPORTANT
         
            //con2 = Myfunc.deleteOrder_by_OrderID(jLabel_orderID.getText());
            con2 = Myfunc.deleteOrder_by_OrderID(jLabel_orderID.getText(),false);
           //JOptionPane.showMessageDialog(null,"ORDER DELETED!");
            /*
                you don't need to delete anything from the order_detail table
                and the transaction_table bcoz they reference the order_table using foriegn key
                constraint "CASCADE ON DELETE"
                so you need to just delete order from the order_table..rest the database will do
            */
            //con3 = Myfunc.subtractOrderForCustomer(jLabel_customerID.getText(),Float.parseFloat(numberOnlyTotal));
            JOptionPane.showMessageDialog(null, "Order with ID : " + jLabel_orderID.getText() + " Deleted!");
        /*    if(con1 != null)
            {
                con1.commit();
                con1.close();
            }*/
        
            if(con2 != null)
            {
                con2.commit();
                con2.close();
            }
            con.commit();
            con.close();
            //dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        //exit();
        }catch(Exception e)
        {
            try {
                if(con != null)
                con.rollback(savepoint);
            } catch (SQLException ex) {
                Logger.getLogger(SELECTED_ORDER_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        finally
        {
            //for(int i = 0 ; i < rows ; i++) {try { if(conArray[i] != null)  conArray[i].close(); } catch(SQLException e){}}
            //try { if(con1 != null)  con1.close(); } catch(SQLException e){}
            try { if(con2 != null)  con2.close(); } catch(SQLException e){}
            //try { if(con3 != null)  con3.close(); } catch(SQLException e){}
            try { if(con != null)  con.close(); } catch(SQLException e){}
        }
        this.dispose();
    }//GEN-LAST:event_jButton_deleteOrderActionPerformed

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SELECTED_ORDER_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SELECTED_ORDER_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SELECTED_ORDER_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SELECTED_ORDER_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
/*        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELECTED_ORDER_FORM().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancelOrder;
    private javax.swing.JButton jButton_deleteOrder;
    private javax.swing.JButton jButton_generateReceipt;
    private javax.swing.JButton jButton_payment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_balance;
    private javax.swing.JLabel jLabel_customerID;
    private javax.swing.JLabel jLabel_customerName;
    private javax.swing.JLabel jLabel_discount;
    private javax.swing.JLabel jLabel_orderDate;
    private javax.swing.JLabel jLabel_orderID;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_order;
    // End of variables declaration//GEN-END:variables
}
